export async function getGithubUser(token: string) {
  const res = await fetch('https://api.github.com/user', {
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github.v3+json',
    },
  });
  if (!res.ok) throw new Error('Failed to fetch github user');
  return res.json();
}

export async function checkAndCreateRepo(token: string, username: string, repo: string) {
  // Check if repo exists
  const checkRes = await fetch(`https://api.github.com/repos/${username}/${repo}`, {
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github.v3+json',
    },
  });

  if (checkRes.ok) return; // Repo exists

  if (checkRes.status === 404) {
    // Create repo
    const createRes = await fetch('https://api.github.com/user/repos', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${token}`,
        Accept: 'application/vnd.github.v3+json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        name: repo,
        description: 'My DSA Tracker Solutions',
        private: false, // Default to public for bragging rights, could be configured
        auto_init: false,
      }),
    });

    if (!createRes.ok) {
      throw new Error('Failed to create repository');
    }

    // Push custom README.md
    const readmeContent = `# DSA Sync Solutions — @${username}

> Synced automatically from [DSA Sync](http://localhost:3000) · Repository: \`${repo}\`

---

## What is this?

This repository is automatically populated with accepted solutions using the **GitHub Sync** feature from DSA Sync.

---

## How GitHub Sync works

1. **Connect your GitHub account** on your profile page.
2. **Auto-commit** — every time you submit a solution, it is pushed here automatically.
3. **Bulk Sync** — push all your past solutions at once from the GitHub settings page.

---

## Repository structure

Solutions are organized by difficulty, then problem title. Each submission is stored as a separate file:

\`\`\`
<difficulty>/
  <problem-title>.md
\`\`\`

**Example:**
\`\`\`
Easy/Two-Sum.md
Medium/Add-Two-Numbers.md
\`\`\`

---

*Generated by DSA Sync*
`;

    const encodedReadme = Buffer.from(readmeContent).toString('base64');

    // Wait a brief moment to ensure repo is ready for commits
    await new Promise(resolve => setTimeout(resolve, 1000));

    await fetch(`https://api.github.com/repos/${username}/${repo}/contents/README.md`, {
      method: 'PUT',
      headers: {
        Authorization: `Bearer ${token}`,
        Accept: 'application/vnd.github.v3+json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        message: 'Initial commit: Add README.md',
        content: encodedReadme,
      }),
    });
  } else {
    throw new Error('Error checking repository');
  }
}

export async function pushProblemToGithub({
  token,
  username,
  repo,
  problemTitle,
  difficulty,
  url,
  code = '',
  notes = '',
  language = 'txt'
}: {
  token: string;
  username: string;
  repo: string;
  problemTitle: string;
  difficulty: string;
  url: string;
  code?: string;
  notes?: string;
  language?: string;
}) {
  await checkAndCreateRepo(token, username, repo);

  // Normalize file name
  const safeTitle = problemTitle.replace(/[^a-zA-Z0-9- ]/g, '').trim().replace(/\s+/g, '-');
  const path = `${difficulty}/${safeTitle}.md`;

  // Check if file already exists to get its SHA (required for updating)
  const fileCheckRes = await fetch(`https://api.github.com/repos/${username}/${repo}/contents/${path}`, {
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github.v3+json',
    },
  });

  let sha: string | undefined;
  if (fileCheckRes.ok) {
    const fileData = await fileCheckRes.json();
    sha = fileData.sha;
  }

  // Construct markdown content
  const content = `# ${problemTitle}

## Problem Link
[${problemTitle}](${url})

## Difficulty
${difficulty}

## Notes
${notes || 'No notes provided.'}

## Code
\`\`\`${language}
${code || '// No code provided'}
\`\`\`
`;

  // Encode to base64
  const encodedContent = Buffer.from(content).toString('base64');

  // Push to github
  const updateRes = await fetch(`https://api.github.com/repos/${username}/${repo}/contents/${path}`, {
    method: 'PUT',
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github.v3+json',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      message: `Sync: ${problemTitle}`,
      content: encodedContent,
      sha: sha // If undefined, github creates a new file. If present, it updates.
    }),
  });

  if (!updateRes.ok) {
    const errData = await updateRes.json().catch(() => null);
    throw new Error(`Failed to push to GitHub: ${errData?.message || updateRes.statusText}`);
  }

  return updateRes.json();
}
